### ISSUE TITLE
Using 1.7 with Gorilla Mux causes memory leak

### ISSUE THREAD

**Issue by jprobinson** [NYTimes/gizmo#74]
gorilla/mux has build tags that opt to use the new/native `context` package for 1.7. 

Unfortunately, Gizmo's `server.Router` implementation uses `gorilla/context` under the hood to allow `httprouter` to pass parameters. This leads to a massive memory leak when running with 1.7 as the `gorilla/context` never gets cleared.

**Comment by jprobinson** [comment]
This has been resolved.

**Comment by oliver-nyt** [comment]
Just tried updating to 1.7 but still running into this issue.

I'm using the latest versions of: 
- gizmo sha `5d6cf612a51d81e2353489b56eee93ec811d797a`
- gorilla/context` 08b5f424b9271eedf6f9f0ce86cb9396ed337a42`

and after serving several thousands requests I still see heap profile issues:
```
11948.29kB 22.77% 22.77% 11948.29kB 22.77%  github.com/gorilla/context.Set
11266.56kB 21.47% 44.24% 11266.56kB 21.47%  net/textproto.(*Reader).ReadMIMEHeader
 8704.73kB 16.59% 60.82%  8704.73kB 16.59%  context.WithCancel
 6657.52kB 12.69% 73.51% 21508.48kB 40.98%  net/http.readRequest

...
```

**Comment by jprobinson** [comment]
Looks like I missed some gorilla/context use in there: https://github.com/NYTimes/gizmo/blob/ae909e7e43a755c0f6c8bbdeb147ae158a78d48d/server/simple_server.go#L328-L332

I'll make another PR to cut that out.

**Comment by jprobinson** [comment]
Should should be resolved with PR #76.
